export const APIConst = {
PATH: '/',
// LOGIN: '/api/auth/signin',
APPDATA_YEARS:'/api/app/years',
// APPDATA_CITIES:'/api/app/cities',
// APPDATA_DISTRICTS:'/api/app/districts',
// APPDATA_STATES:'/api/app/states',
//----- new Api---//
APPDATA_CITIES:'api/Cities',
APPDATA_DISTRICTS:'api/Districts',
APPDATA_STATES:'api/States',
APPDATA_AREAS: 'api/AreaMaster',
APPDATA_PINCODES:'api/CityPincodes',
NEW_LTOTYPES:'api/LTOTypes',
NEW_LTOS:'api/LTOS',
NEW_LTOPrefix:'api/LTOPrefix',
ADMINREG:'api/Firm',
FirmUser:'api/FirmUser',
FirmLtos:'api/FirmLtos',
AccountLtos:'api/AccountLtos',
NoCityAccounts:'api/AccMaster/AccountWithNoCities',
FirmGroup:'api/FirmGroup',
FirmRoles: 'api/FirmRoles',
FirmDetailsByFirmId: 'api/Firm/FirmDetailsByFirmId',
isFirmAliasExisting:'api/Firm/isFirmAliasExisting',
getFirmLtos:'api/FirmLtos',
LOGIN:'api/Login',
// FORGOTPASSWORD: 'api/Login/OTPVerificationAndUpdatingTheNewPassword',
FirmDetailsByFirmGroupId:'api/Firm/FirmDetailsByFirmGroupId',
FirmMenus:'api/FirmMenus',
FirmYear:'api/FirmYear',
PRODMASTERTYPE: 'api/ProductMasterTypes/GetProductMasterTypesByPMType',
ProductMasterTypes:'api/ProductMasterTypes',
MASTERS_MANUFACTURERS:'api/MfgMaster',
UPDATECITY:'api/AccMaster/MapAccountsAndCities',
COMPANYGROUP: 'api/CompanyGroups',
COMPANY: 'api/CompanyMaster',
CUSTOMPRODUCTS: 'api/ProductMaster',
GETCUSTOMPRODUCTS:'api/ProductMaster/SearchProductDetails',
PRODPACKMASTER: 'api/ProdPackMaster',
TAXSLABS: 'api/TaxSlabs',
SCHEDULE: 'api/ScheduleMaster',
MainSchedules: 'api/ScheduleMaster/MainSchedules',
AREAS: 'api/AreaMaster', 
// CUSTOMACCOUNTS: 'api/AccMaster/SearchAccMaster',
HSNMASTER: 'api/HsnMaster',
FirmUsers: 'api/FirmUsers',
TAXSTAKES: 'api/TaxStakes',
TAXCATEGORY: 'api/taxCategory',
CUSTOMACCOUNTS: 'api/AccMaster/SearchAccMaster',
POSTACCOUNTS:'api/AccMaster',
PURCHASEENTRYHEAD: 'api/InwardHead',
GetFirmPreferences:'api/FirmPreferences/GetFirmPreferences',
InwardFinalSave:'api/InwardFinalSave',
getAccountCopyData:'api/FinTranReports/AccountCopy',
AccountCopyAccoounts:'api/FinTranReports/AccountCopyAccounts',
//----- end new api

CHANGE_PASSWORD: 'api/user/changePassword',
LOGGED_IN_USER_DETAILS: 'api/user',
ALL_ROLES: 'api/role',
ROLE_MENUS: '/menus',
ALL_MENUS: '/api/menu',
COMPANY_DIVISON: '/api/masters/products/companyDivisionMaster',
// COMPANY: '/api/masters/products/companyMaster',
FIRM_NAME: '/api/app/firmName',
COMPANYDIVISIONMASTER: '/api/masters/products/companyDivisionMaster',
// PRODMASTERTYPE: 'api/ProductMasterTypes/GetProductMasterTypesByPMType',
// PRODPACKMASTER: '/api/masters/products/prodPackMaster',
// COMPANYGROUP: '/api/masters/products/comGroups',
// MASTERS_MANUFACTURERS:'/api/masters/products/manufacturers',
// TAXSLABS: '/api/masters/tax/taxSlabs',
TAXTYPEMASTER: '/api/masters/tax/taxTypeMaster',
// TAXCATEGORY: '/api/masters/tax/taxCategory',
// TAXSTAKES: '/api/masters/tax/taxStakes',
// SCHEDULE: '/api/masters/accounts',
// AREAS: '/api/masters/accounts',
// CUSTOMPRODUCTS: '/api/masters/products/productMaster',
// CUSTOMACCOUNTS: '/api/masters/accounts/AccountMasters',
LTOACCOUNTS: '/api/app/LtosByFirmTypeAndLtoType/1',
TRANTYPEHEAD: 'api/TranTypeHead',
TRANTYPEDETAIL: 'api/TranTypeDetail',
TABLEMETATABLE: '/api/masters/accounts/TableMetaData',
LOOKUPTABLE: '/api/masters/accounts/LookUpName',
BANKS: '/api/app/banks',
BANKIFSCCODE: 'api/app/bank',
// HSNMASTER: '/api/masters/products/hsnMaster',
PINCODES: '/api/app/PincodesByCity',
TRANSPORT: 'api/masters/accounts/transport',
// PURCHASEENTRYHEAD: '/api/transactions/inward/head',
// PURCHASEENTRYDETAIL:'/api/transactions/inward/detail',
PURCHASEENTRYDETAIL:'api/InwardDetail',
CUSTOMACCOUNTSEARCH: '/api/masters/accounts/accountSearch',
FIRMPREFERENCE: '/api/firm/firmPrefrencesById/1',
CUSTOMPRODUCTSEARCH:'api/ProductMaster/SearchProductDetails',
GetStockByProducts:'api/InwardDetail/GetStockByProducts',
// CUSTOMPRODUCTSEARCH:'api/masters/products/productSearch',
//   FIRMTYPES: '/api/firm/types',
FIRMTYPES: 'api/FirmType', 
FIRMDETAILS: 'api/firm/types/ltoprefix',
GETBANKS:'api/Banks',
GETIFSC:'api/BankIfsc',
CUSTOMACCOUNTBYNAME: '/api/masters/accounts/accountSearch',
// Inward 
INWARDHEADLIST: '/api/transactions/inward/head',
// INWARDHEADDETAILS: '/api/transactions/inward/details',
INWARDHEADDETAILS: 'api/InwardDetail/GetInwardFullDetails',
INWARDDETAILFORM: '/api/OutwardHead',
INWARDRETURNBATCH: '/api/transactions/inward/batch',
// https://ebusiness-coreapi-dev.azurewebsites.net/api/OutwardHead 
OUTWARDDELETE: '/api/OutwardHead',

OUTWARDENTRYHEAD: 'api/OutwardHead',
OUTWARDHEADLIST: '/api/OutwardHead',
CUSTOMPRODUCTBYBATCH : '/api/transactions/inward/batch',
OUTWARDENTRYDETAIL:'api/OutwardDetail',
TRANDATE:'api/transactions/inward/tranDate',
TRANDATE_v1:'/api/InwardHead/GetLastInwardDateByTranTypeId',
saleTranDate:'api/OutwardHead/GetLastOutwardDateByTranTypeId',
VALIDATEINVOICE:'/api/transactions/inward/validateInvoice',
VALIDATEINVOICE2:'/api/InwardHead/ValidateInvoice',
OUTWARDENTRYDETAILLIST: 'api/OutwardDetail/GetOutwardFullDetails',
OUTWARDENTRYFINALSAVE: 'api/OutwardFinalSave',
FIRM:'/api/firm/firm',
GetInwardHead:'api/InwardHead/GetInwardHead',
OUTWARDHEAD :'api/OutwardHead/GetOutwardHead',
invoicePDF:'api/OutwardHead/GenerateInvoicePDF',
//Purchase Register //
GetPurachseRegister:'api/InwardReports/PurchaseRegister',
GetProductSalesHistory : 'api/InwardHead/GetProdcutSalesHistory',
GetCustomerProductSalesHistory : 'api/InwardHead/GetCustomerSalesHIstory',
GetProductPURHistory: 'api/InwardHead/GetProdPurHistory',
GetSupplierPurchaseHistory: 'api/InwardHead/GetSupplierPurchaseHistory',
GetSupplierPurchaseHistoryBatch: 'api/InwardHead/GetSupplierPurchaseHistoryBatch',
GetsaleBatch:'api/InwardHead/GetCustomerSalesHIstoryBatch',
GetPurachseRegisterExcel:'api/InwardReports/PurchaseRegisterExcel',
//Sale Register //
GetSaleRegister:'api/OutwardReports/SalesRegister',
GetSaleRegisterExcel:'api/OutwardReports/SalesRegisterExcel',
ORDERHEAD:'api/OrdHead',
ORDERHEADUPDATE:'api/OrdHead/ordHeadId',
ORDERHEADFULLDETAILS:'api/OrdHead/GetFullOrderDetails',
ORDERDETAIL: 'api/OrdDetail',
ORDERDETAILUPDATE: 'api/OrdDetail/ordDetailId',

// admin Reg
// ADMINREG:'/api/admin/reg',

//Finance  componenet  ------------12-04-2-241///

CASHVOUCHER : '/api/FinTran/tranTypeHeadId',   
CASHRECIEPTSAVE : '/api/FinTran',
CASHRECIEPTDELETE : '/api/FinTran/finTranId',
CASHRECIEPTEDIT : '/api/FinTran/finTranId',
CASHLISTDELETE : '/api/FinTran/finTranHeadId',
CASHRECEIPTUPDATE : '/api/FinTran/finTranId',
CASHLISTEDIT : '/api/FinTran/GetFinTranDetailsByHeadId',
CASHCONTRAGET : '/api/FinTran/GetContraAccount',
CASHRECEIPTREGISTERGENERATE:'api/FinTranReports/FinTranRegister',
// CASHRECIEPTEDIT : 'api/FinTran/finTranHeadId',
GENERATEEXCEL:'api/FinTranReports/FinTranRegisterExcel',
// Stock reports //
companiesMaster:'/api/CompanyMaster',
companiesGroups:'/api/CompanyGroups',
stockStatement:'api/StockReports/StockStatement',
stockPosition:'api/StockReports/StockPostion',
stockLedger :'api/StockReports/StockLedger',
stockPositionExcel:'api/StockReports/StockPositionExcel',
stockStatementExcel:'api/StockReports/StockStatementExcel',
accountCopyExcel:'api/FinTranReports/AccountCopyExcel',
expiryStockSummary:'api/StockReports/GetExpiryStockSummary',
expiryStockSlots:'api/StockReports/GetExpiryStockSlots',
expiryStockSlotsExcel:'/api/StockReports/GetExpiryStockSlotsExcel',
dashBoardData:'api/StockReports/GetDashBoardData',
batchesByProductId:'api/StockReports/GetBatchesByProductId',
batchWiseStockLedger:'api/StockReports/GetBatchWiseStockLedger'
};


export const RouteConst={
    PATH: '/',
    LOGIN: 'login',
    CHANGE_PASSWORD: 'changed-Password',
    USER: 'user',
    USER_PROFILE:'administration/profile',
    USER_PREF:'user/preference',
    ADMINISTRATION: 'administration',
    PHARMA: 'pharma',
    DASHBOARD: 'home',
    ADMIN: 'admin',

};


export const AppConst ={
    DATE_FORMAT: 'yyyy-MM-dd'
}

export const PurchasePrefix = 'PUR';
export const PURCHASERETURNPREFIX = 'PRET';
export const SalePrefix = 'SAL';
export const SaveText = 'Save';
export const UpdateText = 'Update';
export const SaveContinueText = 'Save & Continue';
export const SaveCloseText = 'Save & Close';
export const UpdateContinueText = 'Update & Continue';
export const UpdateCloseText = 'Update & Close';
export const addItem = 'Add Item';
export const DEFAULT_EMPTY_FIELD = '- -';