import { NgModule } from '@angular/core';
import { MatRadioModule, MatButtonModule, MatToolbarModule, MatSelectModule, 
  MatTabsModule, MatInputModule, MatProgressSpinnerModule, MatChipsModule, 
  MatSidenavModule, MatCheckboxModule, MatListModule, MatMenuModule, MatIconModule, MatTooltipModule,
   MatSnackBarModule, MatSlideToggleModule, MatDividerModule, MatAutocompleteModule, MatTableModule,
    MatDialogModule, MatBadgeModule, MatBottomSheetModule, MatButtonToggleModule, MatStepperModule,
     MatDatepickerModule, MatNativeDateModule, MatGridListModule, MatPaginatorModule, 
     MatProgressBarModule, MatRippleModule, MatSliderModule, MatSortModule, MatTreeModule, 
     MatFormFieldModule, 
     MatExpansionModule,
     MatCardModule} from '@angular/material';
import { MatTableFilterModule } from 'mat-table-filter';
import { MatRowKeyboardSelectionModule } from 'mat-row-keyboard-selection';
import { MatMomentDateModule } from "@angular/material-moment-adapter";
import { NgxMatSelectSearchModule } from 'ngx-mat-select-search';


@NgModule({
  declarations: [],
  imports: [
    MatRadioModule,
    MatExpansionModule,
    MatToolbarModule,
    MatTabsModule,
    MatProgressSpinnerModule,
    MatChipsModule,
    MatFormFieldModule,
    MatInputModule,
    MatIconModule,
    MatButtonModule,
    MatMenuModule,
    MatCardModule,
    MatSidenavModule,
    MatCheckboxModule,
    MatListModule,
    MatIconModule,
    MatSnackBarModule,
    MatSlideToggleModule,
    MatDividerModule,
    MatAutocompleteModule,
    MatDialogModule,
    MatBadgeModule,
    MatBottomSheetModule,
    MatButtonToggleModule,
    MatStepperModule,
    MatGridListModule,
    MatProgressBarModule,
    MatRippleModule,
    MatSliderModule,
    MatSortModule,
    MatTreeModule,    
    MatTableModule,
    MatPaginatorModule,
    MatTooltipModule,
    MatDatepickerModule,
    MatSelectModule,
    MatTableFilterModule,    
    MatRowKeyboardSelectionModule,
    MatMomentDateModule,
    NgxMatSelectSearchModule
  ],
  exports: [
    MatRadioModule,
    MatExpansionModule,
    MatToolbarModule,
    MatTabsModule,
    MatProgressSpinnerModule,
    MatChipsModule,
    MatFormFieldModule,
    MatInputModule,
    MatIconModule,
    MatButtonModule,
    MatMenuModule,
    MatCardModule,
    MatSidenavModule,
    MatCheckboxModule,
    MatListModule,
    MatIconModule,
    MatSnackBarModule,
    MatSlideToggleModule,
    MatDividerModule,
    MatAutocompleteModule,
    MatDialogModule,
    MatBadgeModule,
    MatBottomSheetModule,
    MatButtonToggleModule,
    MatStepperModule,
    MatGridListModule,
    MatProgressBarModule,
    MatRippleModule,
    MatSliderModule,
    MatSortModule,
    MatTreeModule,    
    MatTableModule,
    MatPaginatorModule,
    MatTooltipModule,
    MatDatepickerModule,
    MatSelectModule, 
    MatTableFilterModule,    
    MatRowKeyboardSelectionModule,
    MatMomentDateModule,
    NgxMatSelectSearchModule
  ],  providers: [  
    MatDatepickerModule,
    MatNativeDateModule  
  ]
})
export class MaterialModule { }
